### ISSUE TITLE
Element-plus 组件在 远程组件中无法使用

### ISSUE THREAD

**Issue by WeiYYin** [hel-eco/hel-tpl-remote-vue3-comps-ts#3]
在 组件中使用了 Element-plus 的组件，本地调试正常。
发布unpkg后，通过 懒加载加载组件，组件加载失败。
https://codesandbox.io/s/demo-load-remote-vue3-comp-forked-90i0fw?file=/src/App.vue

<img width="1916" alt="image" src="https://user-images.githubusercontent.com/33323771/206185708-56f1eaed-315a-4ac9-a839-b5fcc7b90f6b.png">

**Comment by fantasticsoul** [comment]
收到，我查看下

**Comment by fantasticsoul** [comment]
我打开你给的链接，没有发现报错信息，你在群里么，欢迎群里沟通下

**Comment by WeiYYin** [comment]
> 我打开你给的链接，没有发现报错信息，你在群里么，欢迎群里沟通下

是element-plus 中使用的一个库 没打包进去，换了一个方式处理了。  感谢🥳🥳
